
from ai_processor import extract_action_items

transcript = """
Okay, uh, good morning everyone… yeah, let’s get started… so I think we should first go over what happened in the last sprint… Rahul, do you want to begin… Yeah sure… so from the backend side things are mostly stable… authentication and user modules are working fine now… but the payment service is still not performing well under load… we noticed delays especially during peak usage… so we probably need to look into optimizing that soon… otherwise it might cause issues later… Right, that makes sense… Sneha, what’s happening on the frontend side… Yeah, so honestly the delay this week was mainly because of design updates… we had to rework the dashboard layout and some parts of the profile section… it took longer than expected… but now most of the structure is ready… we still need to finish a few UI components and also improve responsiveness because it’s still lagging on some devices… Okay… yeah that’s important… Karan, anything from the client side… Yeah, so after the last demo the client mentioned that the app feels slightly slow… especially when switching between pages… they also said the experience isn’t as smooth as they expected… and they were asking if we could include some kind of analytics dashboard in the next phase… so we’ll need to think about that and define what exactly needs to be built… Alright… Priya, what about QA… Yeah… we’ve been seeing repeated issues in the login flow… especially with edge cases… like when users enter incorrect inputs multiple times… the system isn’t handling it properly… also some bugs that we fixed earlier are coming back… so I think we need better test coverage and maybe add regression testing to avoid this… Yeah, that’s been slowing us down… Exactly… Okay… Arjun, data side updates… Yeah, so ingestion speed has improved after the last changes… but there are still inconsistencies in the data… sometimes values don’t match expected results… we’re still trying to figure out why that’s happening… probably need to strengthen validation checks there… Hmm okay… Vikram, anything from your side… Yeah… I mean looking at the current system… it works, but I’m a bit concerned about scalability… as usage grows, this structure might not hold up well… maybe we should start thinking about making the architecture more modular… otherwise it could become difficult to maintain later… Yeah, that’s a good point… Neha, anything from budget side… No major issues for now… everything is within limits… just make sure if we’re adding new tools or features, we review costs beforehand… Sure… Meera, anything from HR… Yeah… just one thing… we’ve noticed some people are working longer hours recently… especially during the last week… so maybe we should keep an eye on workload distribution… don’t want anyone burning out… Yeah, agreed… Alright… so overall I think we have a few things that need attention… mainly performance issues, testing gaps, and some pending UI work… let’s just make sure we address these before the next review… Also, we should probably reconnect next week and see where things stand… Yeah, that sounds good… Alright, thanks everyone… let’s stay aligned and keep communication clear…

"""

# ONLY print final result
print(extract_action_items(transcript))





# from ai_processor import extract_action_items

# # sample transcript (replace later)
# transcript = """
# Okay, uh, good morning everyone… yeah, let’s get started… so I think we should first go over what happened in the last sprint… Rahul, do you want to begin…

# Yeah sure… so from the backend side things are mostly stable… authentication and user modules are working fine now… but the payment service is still not performing well under load… we noticed delays especially during peak usage… so we probably need to look into optimizing that soon… otherwise it might cause issues later…

# Right, that makes sense… Sneha, what’s happening on the frontend side…

# Yeah, so honestly the delay this week was mainly because of design updates… we had to rework the dashboard layout and some parts of the profile section… it took longer than expected… but now most of the structure is ready… we still need to finish a few UI components and also improve responsiveness because it’s still lagging on some devices…

# Okay… yeah that’s important… Karan, anything from the client side…

# Yeah, so after the last demo the client mentioned that the app feels slightly slow… especially when switching between pages… they also said the experience isn’t as smooth as they expected… and they were asking if we could include some kind of analytics dashboard in the next phase… so we’ll need to think about that and define what exactly needs to be built…

# Alright… Priya, what about QA…

# Yeah… we’ve been seeing repeated issues in the login flow… especially with edge cases… like when users enter incorrect inputs multiple times… the system isn’t handling it properly… also some bugs that we fixed earlier are coming back… so I think we need better test coverage and maybe add regression testing to avoid this…

# Yeah, that’s been slowing us down…

# Exactly…

# Okay… Arjun, data side updates…

# Yeah, so ingestion speed has improved after the last changes… but there are still inconsistencies in the data… sometimes values don’t match expected results… we’re still trying to figure out why that’s happening… probably need to strengthen validation checks there…

# Hmm okay…

# Vikram, anything from your side…

# Yeah… I mean looking at the current system… it works, but I’m a bit concerned about scalability… as usage grows, this structure might not hold up well… maybe we should start thinking about making the architecture more modular… otherwise it could become difficult to maintain later…

# Yeah, that’s a good point…

# Neha, anything from budget side…

# No major issues for now… everything is within limits… just make sure if we’re adding new tools or features, we review costs beforehand…

# Sure…

# Meera, anything from HR…

# Yeah… just one thing… we’ve noticed some people are working longer hours recently… especially during the last week… so maybe we should keep an eye on workload distribution… don’t want anyone burning out…

# Yeah, agreed…

# Alright… so overall I think we have a few things that need attention… mainly performance issues, testing gaps, and some pending UI work… let’s just make sure we address these before the next review…

# Also, we should probably reconnect next week and see where things stand…

# Yeah, that sounds good…

# Alright, thanks everyone… let’s stay aligned and keep communication clear…
# """

# result = extract_action_items(transcript)

# print("\n✅ Final Action Items:")
# for item in result:
#     print("-", item)